# Generated by Django 4.0.2 on 2022-02-10 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interviewscheduler', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interview',
            old_name='author',
            new_name='candidate',
        ),
    ]
