# Generated by Django 4.0.2 on 2022-02-14 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviewscheduler', '0006_alter_candidate_id_alter_interview_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interview',
            name='scheduled_time',
            field=models.DateTimeField(),
        ),
    ]
